name: idol
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  flutter_redux: ^0.7.0
  dio: ^3.0.7
  redux_logging: ^0.4.0
  logging: ^0.11.4
  flutter_snake_navigationbar: ^0.4.2
  # flutter_secure_storage: ^3.3.5
  flustars: ^0.3.3
  carousel_slider: ^2.3.1
  animations: ^1.1.2
  pull_to_refresh: ^1.6.3
  flutter_easyloading: ^2.2.2

  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^4.1.3
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets:
  - assets/images
  - assets/texts
  fonts:
  - assets/fonts
flutter:
  uses-material-design: true
  assets:
  - assets/images/dashboard/bg_withdraw.png
  - assets/images/dashboard/bg_withdraw.webp
  - assets/images/dashboard/bg_withdraw_failure.webp
  - assets/images/dashboard/bg_withdraw_success.webp
  - assets/images/main/bg_splash.jpg
  - assets/images/main/ic_tab_biolinks_normal.png
  - assets/images/main/ic_tab_biolinks_selected.png
  - assets/images/main/ic_tab_dashboard_normal.png
  - assets/images/main/ic_tab_dashboard_selected.png
  - assets/images/main/ic_tab_inbox_normal.png
  - assets/images/main/ic_tab_inbox_selected.png
  - assets/images/main/ic_tab_store_normal.png
  - assets/images/main/ic_tab_store_selected.png
  - assets/images/main/ic_tab_supply_normal.png
  - assets/images/main/ic_tab_supply_selected.png
