name: idol
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.1
  flutter_redux: ^0.7.0
  dio: ^3.0.7
  redux_logging: ^0.4.0
  logging: ^0.11.4
  flutter_snake_navigationbar: ^0.4.2
  flustars: ^0.3.3
  carousel_slider: ^3.0.0
  animations: ^1.1.2
  pull_to_refresh: ^1.6.3
  flutter_easyloading: ^2.2.2
  flutter_swiper: ^1.1.6
  video_player: ^1.0.1
  flutter_slidable: ^0.5.7
  image_picker: ^0.6.7+21
  crop: any
  image_gallery_saver: any
  permission_handler: any
  flutter_staggered_grid_view: ^0.3.2
  r_dart_library: ^0.2.1
  webview_flutter: ^1.0.7
  flutter_secure_storage: ^3.3.5
  share: ^0.6.5+4
  ecomshare:
    path: plugins/ecomshare
dependency_overrides:
  flutter_svg: 0.20.0-nullsafety.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^4.1.3
flr:
  core_version: 3.1.0
  dartfmt_line_length: 80
  assets:
  - assets/images
  - assets/texts
  fonts:
  - assets/fonts
flutter:
  uses-material-design: true
  assets:
  - assets/images/bg_common_error.png
  - assets/images/dashboard/bg_withdraw.png
  - assets/images/dashboard/bg_withdraw.webp
  - assets/images/dashboard/bg_withdraw_failure.webp
  - assets/images/dashboard/bg_withdraw_success.webp
  - assets/images/dashboard/ic_complete_rewards.png
  - assets/images/ic_share_copy_link.png
  - assets/images/ic_share_download.png
  - assets/images/ic_share_facebook.png
  - assets/images/ic_share_instagram.png
  - assets/images/ic_share_more.png
  - assets/images/ic_share_twitter.png
  - assets/images/main/bg_login_signup.png
  - assets/images/main/ic_logo.png
  - assets/images/main/ic_password_visibility.png
  - assets/images/main/ic_password_visibility_off.png
  - assets/images/main/ic_tab_biolinks_normal.png
  - assets/images/main/ic_tab_biolinks_selected.png
  - assets/images/main/ic_tab_dashboard_normal.png
  - assets/images/main/ic_tab_dashboard_selected.png
  - assets/images/main/ic_tab_inbox_normal.png
  - assets/images/main/ic_tab_inbox_selected.png
  - assets/images/main/ic_tab_store_normal.png
  - assets/images/main/ic_tab_store_selected.png
  - assets/images/main/ic_tab_supply_normal.png
  - assets/images/main/ic_tab_supply_selected.png
  - assets/images/main/ic_whatsapp.png
  - assets/images/main/launch_background.webp
  - assets/images/shoplink/ic_change_avatar.png
  - assets/images/shoplink/ic_edit.png
  - assets/images/store/bg_header.png
  - assets/images/store/default_portrait.png
  - assets/images/store/ic_settings_contact.png
  - assets/images/store/ic_settings_email.png
  - assets/images/store/ic_settings_faq.png
  - assets/images/store/ic_settings_privacy.png
  - assets/images/store/ic_settings_rate_us.png
  - assets/images/store/ic_settings_set_password.png
  - assets/images/store/ic_tab_category_selected.png
  - assets/images/store/ic_tab_category_unselected.png
  - assets/images/store/ic_tab_product_selected.png
  - assets/images/store/ic_tab_product_unselected.png
  - assets/images/supply/ic_goods_share.png
  - assets/images/supply/ic_tab_supplier_hot_product_selected.png
  - assets/images/supply/ic_tab_supplier_hot_product_unselected.png
  - assets/images/supply/ic_tab_supplier_new_product_selected.png
  - assets/images/supply/ic_tab_supplier_new_product_unselected.png
  - assets/images/supply/pause.png
  - assets/images/supply/play.png
