var linkDomain = 'https://olaak.com/';
var videoUrls = ['https://oss.wqiang.fun/video/test.mp4'];
var androidAppId = 'me.hookar.idol';
var iosAppId = '1560793181';
var emailUsUri = 'mailto:cs@mysocials.shop';
var whatsAppUri = 'whatsapp://send?phone=+16625080411';
var whatsAppUri2 = 'whatsapp://wa.me/+16625080411?text=Hello';
var faqUri = linkDomain + 'faq.htm';
var termsConditionsUri = linkDomain + 'terms_conditions.htm';
var cookiePolicyUri = linkDomain + 'cookie_policy.htm';
var privacyPolicyUri = linkDomain + 'privacy_policy.htm';
var customerService = 'https://www.facebook.com/groups/821302222143641';
