var linkDomain = 'https://mypik.shop/';
var videoUrls = ['https://oss.wqiang.fun/video/test.mp4'];
var iosAppId = '1234567890';
var emailUsUri = 'mailto:cs@mysocials.shop';
var whatsAppUri = 'whatsapp://send?phone=+16625080411';
var whatsAppUri2 = 'whatsapp://wa.me/+16625080411?text=Hello';
var faqUri = linkDomain + 'faq.htm';
var termsConditionsUri = linkDomain + 'terms_conditions.htm';
var cookiePolicyUri = linkDomain + 'cookie_policy.htm';
var privacyPolicyUri = linkDomain + 'privacy_policy.htm';
