// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: idol
  static const package = "idol";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName})
      : assert(assetName != null);

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/images/dashboard/bg_withdraw.png
  // ignore: non_constant_identifier_names
  final bg_withdraw = const AssetResource(
      "assets/images/dashboard/bg_withdraw.png",
      packageName: null);

  /// asset: assets/images/dashboard/bg_withdraw.webp
  // ignore: non_constant_identifier_names
  final bg_withdraw_webp = const AssetResource(
      "assets/images/dashboard/bg_withdraw.webp",
      packageName: null);

  /// asset: assets/images/dashboard/bg_withdraw_failure.webp
  // ignore: non_constant_identifier_names
  final bg_withdraw_failure_webp = const AssetResource(
      "assets/images/dashboard/bg_withdraw_failure.webp",
      packageName: null);

  /// asset: assets/images/dashboard/bg_withdraw_success.webp
  // ignore: non_constant_identifier_names
  final bg_withdraw_success_webp = const AssetResource(
      "assets/images/dashboard/bg_withdraw_success.webp",
      packageName: null);

  /// asset: assets/images/dashboard/ic_complete_rewards.png
  // ignore: non_constant_identifier_names
  final ic_complete_rewards = const AssetResource(
      "assets/images/dashboard/ic_complete_rewards.png",
      packageName: null);

  /// asset: assets/images/main/bg_splash.jpg
  // ignore: non_constant_identifier_names
  final bg_splash_jpg = const AssetResource("assets/images/main/bg_splash.jpg",
      packageName: null);

  /// asset: assets/images/main/ic_tab_biolinks_normal.png
  // ignore: non_constant_identifier_names
  final ic_tab_biolinks_normal = const AssetResource(
      "assets/images/main/ic_tab_biolinks_normal.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_biolinks_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_biolinks_selected = const AssetResource(
      "assets/images/main/ic_tab_biolinks_selected.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_dashboard_normal.png
  // ignore: non_constant_identifier_names
  final ic_tab_dashboard_normal = const AssetResource(
      "assets/images/main/ic_tab_dashboard_normal.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_dashboard_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_dashboard_selected = const AssetResource(
      "assets/images/main/ic_tab_dashboard_selected.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_inbox_normal.png
  // ignore: non_constant_identifier_names
  final ic_tab_inbox_normal = const AssetResource(
      "assets/images/main/ic_tab_inbox_normal.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_inbox_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_inbox_selected = const AssetResource(
      "assets/images/main/ic_tab_inbox_selected.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_store_normal.png
  // ignore: non_constant_identifier_names
  final ic_tab_store_normal = const AssetResource(
      "assets/images/main/ic_tab_store_normal.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_store_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_store_selected = const AssetResource(
      "assets/images/main/ic_tab_store_selected.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_supply_normal.png
  // ignore: non_constant_identifier_names
  final ic_tab_supply_normal = const AssetResource(
      "assets/images/main/ic_tab_supply_normal.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_supply_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_supply_selected = const AssetResource(
      "assets/images/main/ic_tab_supply_selected.png",
      packageName: null);

  /// asset: assets/images/store/bg_header.png
  // ignore: non_constant_identifier_names
  final bg_header = const AssetResource("assets/images/store/bg_header.png",
      packageName: null);

  /// asset: assets/images/store/default_portrait.png
  // ignore: non_constant_identifier_names
  final default_portrait = const AssetResource(
      "assets/images/store/default_portrait.png",
      packageName: null);

  /// asset: assets/images/store/ic_tab_category_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_category_selected = const AssetResource(
      "assets/images/store/ic_tab_category_selected.png",
      packageName: null);

  /// asset: assets/images/store/ic_tab_category_unselected.png
  // ignore: non_constant_identifier_names
  final ic_tab_category_unselected = const AssetResource(
      "assets/images/store/ic_tab_category_unselected.png",
      packageName: null);

  /// asset: assets/images/store/ic_tab_product_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_product_selected = const AssetResource(
      "assets/images/store/ic_tab_product_selected.png",
      packageName: null);

  /// asset: assets/images/store/ic_tab_product_unselected.png
  // ignore: non_constant_identifier_names
  final ic_tab_product_unselected = const AssetResource(
      "assets/images/store/ic_tab_product_unselected.png",
      packageName: null);

  /// asset: assets/images/supply/pause.png
  // ignore: non_constant_identifier_names
  final pause =
      const AssetResource("assets/images/supply/pause.png", packageName: null);

  /// asset: assets/images/supply/play.png
  // ignore: non_constant_identifier_names
  final play =
      const AssetResource("assets/images/supply/play.png", packageName: null);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/images/dashboard/bg_withdraw.png
  // ignore: non_constant_identifier_names
  AssetImage bg_withdraw() {
    return AssetImage(asset.bg_withdraw.keyName);
  }

  /// asset: assets/images/dashboard/bg_withdraw.webp
  // ignore: non_constant_identifier_names
  AssetImage bg_withdraw_webp() {
    return AssetImage(asset.bg_withdraw_webp.keyName);
  }

  /// asset: assets/images/dashboard/bg_withdraw_failure.webp
  // ignore: non_constant_identifier_names
  AssetImage bg_withdraw_failure_webp() {
    return AssetImage(asset.bg_withdraw_failure_webp.keyName);
  }

  /// asset: assets/images/dashboard/bg_withdraw_success.webp
  // ignore: non_constant_identifier_names
  AssetImage bg_withdraw_success_webp() {
    return AssetImage(asset.bg_withdraw_success_webp.keyName);
  }

  /// asset: assets/images/dashboard/ic_complete_rewards.png
  // ignore: non_constant_identifier_names
  AssetImage ic_complete_rewards() {
    return AssetImage(asset.ic_complete_rewards.keyName);
  }

  /// asset: assets/images/main/bg_splash.jpg
  // ignore: non_constant_identifier_names
  AssetImage bg_splash_jpg() {
    return AssetImage(asset.bg_splash_jpg.keyName);
  }

  /// asset: assets/images/main/ic_tab_biolinks_normal.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_biolinks_normal() {
    return AssetImage(asset.ic_tab_biolinks_normal.keyName);
  }

  /// asset: assets/images/main/ic_tab_biolinks_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_biolinks_selected() {
    return AssetImage(asset.ic_tab_biolinks_selected.keyName);
  }

  /// asset: assets/images/main/ic_tab_dashboard_normal.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_dashboard_normal() {
    return AssetImage(asset.ic_tab_dashboard_normal.keyName);
  }

  /// asset: assets/images/main/ic_tab_dashboard_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_dashboard_selected() {
    return AssetImage(asset.ic_tab_dashboard_selected.keyName);
  }

  /// asset: assets/images/main/ic_tab_inbox_normal.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_inbox_normal() {
    return AssetImage(asset.ic_tab_inbox_normal.keyName);
  }

  /// asset: assets/images/main/ic_tab_inbox_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_inbox_selected() {
    return AssetImage(asset.ic_tab_inbox_selected.keyName);
  }

  /// asset: assets/images/main/ic_tab_store_normal.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_store_normal() {
    return AssetImage(asset.ic_tab_store_normal.keyName);
  }

  /// asset: assets/images/main/ic_tab_store_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_store_selected() {
    return AssetImage(asset.ic_tab_store_selected.keyName);
  }

  /// asset: assets/images/main/ic_tab_supply_normal.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_supply_normal() {
    return AssetImage(asset.ic_tab_supply_normal.keyName);
  }

  /// asset: assets/images/main/ic_tab_supply_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_supply_selected() {
    return AssetImage(asset.ic_tab_supply_selected.keyName);
  }

  /// asset: assets/images/store/bg_header.png
  // ignore: non_constant_identifier_names
  AssetImage bg_header() {
    return AssetImage(asset.bg_header.keyName);
  }

  /// asset: assets/images/store/default_portrait.png
  // ignore: non_constant_identifier_names
  AssetImage default_portrait() {
    return AssetImage(asset.default_portrait.keyName);
  }

  /// asset: assets/images/store/ic_tab_category_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_category_selected() {
    return AssetImage(asset.ic_tab_category_selected.keyName);
  }

  /// asset: assets/images/store/ic_tab_category_unselected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_category_unselected() {
    return AssetImage(asset.ic_tab_category_unselected.keyName);
  }

  /// asset: assets/images/store/ic_tab_product_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_product_selected() {
    return AssetImage(asset.ic_tab_product_selected.keyName);
  }

  /// asset: assets/images/store/ic_tab_product_unselected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_product_unselected() {
    return AssetImage(asset.ic_tab_product_unselected.keyName);
  }

  /// asset: assets/images/supply/pause.png
  // ignore: non_constant_identifier_names
  AssetImage pause() {
    return AssetImage(asset.pause.keyName);
  }

  /// asset: assets/images/supply/play.png
  // ignore: non_constant_identifier_names
  AssetImage play() {
    return AssetImage(asset.play.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();
}
