// IT IS GENERATED BY FLR - DO NOT MODIFY BY HAND
// YOU CAN GET MORE DETAILS ABOUT FLR FROM:
// - https://github.com/Fly-Mix/flr-cli
// - https://github.com/Fly-Mix/flr-vscode-extension
// - https://github.com/Fly-Mix/flr-as-plugin
//

// ignore: unused_import
import 'package:flutter/widgets.dart';
// ignore: unused_import
import 'package:flutter/services.dart' show rootBundle;
// ignore: unused_import
import 'package:path/path.dart' as path;
// ignore: unused_import
import 'package:flutter_svg/flutter_svg.dart';
// ignore: unused_import
import 'package:r_dart_library/asset_svg.dart';

/// This `R` class is generated and contains references to static asset resources.
class R {
  /// package name: idol
  static const package = "idol";

  /// This `R.image` struct is generated, and contains static references to static non-svg type image asset resources.
  static const image = _R_Image();

  /// This `R.svg` struct is generated, and contains static references to static svg type image asset resources.
  static const svg = _R_Svg();

  /// This `R.text` struct is generated, and contains static references to static text asset resources.
  static const text = _R_Text();

  /// This `R.fontFamily` struct is generated, and contains static references to static font asset resources.
  static const fontFamily = _R_FontFamily();
}

/// Asset resource’s metadata class.
/// For example, here is the metadata of `packages/flutter_demo/assets/images/example.png` asset:
/// - packageName：flutter_demo
/// - assetName：assets/images/example.png
/// - fileDirname：assets/images
/// - fileBasename：example.png
/// - fileBasenameNoExtension：example
/// - fileExtname：.png
class AssetResource {
  /// Creates an object to hold the asset resource’s metadata.
  const AssetResource(this.assetName, {this.packageName})
      : assert(assetName != null);

  /// The name of the main asset from the set of asset resources to choose from.
  final String assetName;

  /// The name of the package from which the asset resource is included.
  final String packageName;

  /// The name used to generate the key to obtain the asset resource. For local assets
  /// this is [assetName], and for assets from packages the [assetName] is
  /// prefixed 'packages/<package_name>/'.
  String get keyName =>
      packageName == null ? assetName : "packages/$packageName/$assetName";

  /// The file basename of the asset resource.
  String get fileBasename {
    final basename = path.basename(assetName);
    return basename;
  }

  /// The no extension file basename of the asset resource.
  String get fileBasenameNoExtension {
    final basenameWithoutExtension = path.basenameWithoutExtension(assetName);
    return basenameWithoutExtension;
  }

  /// The file extension name of the asset resource.
  String get fileExtname {
    final extension = path.extension(assetName);
    return extension;
  }

  /// The directory path name of the asset resource.
  String get fileDirname {
    var dirname = assetName;
    if (packageName != null) {
      final packageStr = "packages/$packageName/";
      dirname = dirname.replaceAll(packageStr, "");
    }
    final filenameStr = "$fileBasename/";
    dirname = dirname.replaceAll(filenameStr, "");
    return dirname;
  }
}

// ignore: camel_case_types
class _R_Image_AssetResource {
  const _R_Image_AssetResource();

  /// asset: assets/images/avatar.png
  // ignore: non_constant_identifier_names
  final avatar =
      const AssetResource("assets/images/avatar.png", packageName: null);

  /// asset: assets/images/bg_congratulations.png
  // ignore: non_constant_identifier_names
  final bg_congratulations = const AssetResource(
      "assets/images/bg_congratulations.png",
      packageName: null);

  /// asset: assets/images/bg_default_empty_goods.webp
  // ignore: non_constant_identifier_names
  final bg_default_empty_goods_webp = const AssetResource(
      "assets/images/bg_default_empty_goods.webp",
      packageName: null);

  /// asset: assets/images/bg_default_empty_sales_history.webp
  // ignore: non_constant_identifier_names
  final bg_default_empty_sales_history_webp = const AssetResource(
      "assets/images/bg_default_empty_sales_history.webp",
      packageName: null);

  /// asset: assets/images/bg_default_error.png
  // ignore: non_constant_identifier_names
  final bg_default_error = const AssetResource(
      "assets/images/bg_default_error.png",
      packageName: null);

  /// asset: assets/images/bg_default_net_error.webp
  // ignore: non_constant_identifier_names
  final bg_default_net_error_webp = const AssetResource(
      "assets/images/bg_default_net_error.webp",
      packageName: null);

  /// asset: assets/images/dashboard/bg_withdraw.webp
  // ignore: non_constant_identifier_names
  final bg_withdraw_webp = const AssetResource(
      "assets/images/dashboard/bg_withdraw.webp",
      packageName: null);

  /// asset: assets/images/dashboard/bg_withdraw_failure.webp
  // ignore: non_constant_identifier_names
  final bg_withdraw_failure_webp = const AssetResource(
      "assets/images/dashboard/bg_withdraw_failure.webp",
      packageName: null);

  /// asset: assets/images/dashboard/bg_withdraw_success.webp
  // ignore: non_constant_identifier_names
  final bg_withdraw_success_webp = const AssetResource(
      "assets/images/dashboard/bg_withdraw_success.webp",
      packageName: null);

  /// asset: assets/images/dashboard/ic_complete_rewards.png
  // ignore: non_constant_identifier_names
  final ic_complete_rewards = const AssetResource(
      "assets/images/dashboard/ic_complete_rewards.png",
      packageName: null);

  /// asset: assets/images/dashboard/ic_welcome_dialog.png
  // ignore: non_constant_identifier_names
  final ic_welcome_dialog = const AssetResource(
      "assets/images/dashboard/ic_welcome_dialog.png",
      packageName: null);

  /// asset: assets/images/ic_share_copy_link.png
  // ignore: non_constant_identifier_names
  final ic_share_copy_link = const AssetResource(
      "assets/images/ic_share_copy_link.png",
      packageName: null);

  /// asset: assets/images/ic_share_download.png
  // ignore: non_constant_identifier_names
  final ic_share_download = const AssetResource(
      "assets/images/ic_share_download.png",
      packageName: null);

  /// asset: assets/images/ic_share_facebook.png
  // ignore: non_constant_identifier_names
  final ic_share_facebook = const AssetResource(
      "assets/images/ic_share_facebook.png",
      packageName: null);

  /// asset: assets/images/ic_share_instagram.png
  // ignore: non_constant_identifier_names
  final ic_share_instagram = const AssetResource(
      "assets/images/ic_share_instagram.png",
      packageName: null);

  /// asset: assets/images/ic_share_more.png
  // ignore: non_constant_identifier_names
  final ic_share_more =
      const AssetResource("assets/images/ic_share_more.png", packageName: null);

  /// asset: assets/images/ic_share_twitter.png
  // ignore: non_constant_identifier_names
  final ic_share_twitter = const AssetResource(
      "assets/images/ic_share_twitter.png",
      packageName: null);

  /// asset: assets/images/main/bg_login_signup.png
  // ignore: non_constant_identifier_names
  final bg_login_signup = const AssetResource(
      "assets/images/main/bg_login_signup.png",
      packageName: null);

  /// asset: assets/images/main/ic_circle_logo.png
  // ignore: non_constant_identifier_names
  final ic_circle_logo = const AssetResource(
      "assets/images/main/ic_circle_logo.png",
      packageName: null);

  /// asset: assets/images/main/ic_password_visibility.png
  // ignore: non_constant_identifier_names
  final ic_password_visibility = const AssetResource(
      "assets/images/main/ic_password_visibility.png",
      packageName: null);

  /// asset: assets/images/main/ic_password_visibility_off.png
  // ignore: non_constant_identifier_names
  final ic_password_visibility_off = const AssetResource(
      "assets/images/main/ic_password_visibility_off.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_biolinks_normal.png
  // ignore: non_constant_identifier_names
  final ic_tab_biolinks_normal = const AssetResource(
      "assets/images/main/ic_tab_biolinks_normal.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_biolinks_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_biolinks_selected = const AssetResource(
      "assets/images/main/ic_tab_biolinks_selected.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_dashboard_normal.png
  // ignore: non_constant_identifier_names
  final ic_tab_dashboard_normal = const AssetResource(
      "assets/images/main/ic_tab_dashboard_normal.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_dashboard_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_dashboard_selected = const AssetResource(
      "assets/images/main/ic_tab_dashboard_selected.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_inbox_normal.png
  // ignore: non_constant_identifier_names
  final ic_tab_inbox_normal = const AssetResource(
      "assets/images/main/ic_tab_inbox_normal.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_inbox_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_inbox_selected = const AssetResource(
      "assets/images/main/ic_tab_inbox_selected.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_store_normal.png
  // ignore: non_constant_identifier_names
  final ic_tab_store_normal = const AssetResource(
      "assets/images/main/ic_tab_store_normal.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_store_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_store_selected = const AssetResource(
      "assets/images/main/ic_tab_store_selected.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_supply_normal.png
  // ignore: non_constant_identifier_names
  final ic_tab_supply_normal = const AssetResource(
      "assets/images/main/ic_tab_supply_normal.png",
      packageName: null);

  /// asset: assets/images/main/ic_tab_supply_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_supply_selected = const AssetResource(
      "assets/images/main/ic_tab_supply_selected.png",
      packageName: null);

  /// asset: assets/images/main/ic_whatsapp.png
  // ignore: non_constant_identifier_names
  final ic_whatsapp = const AssetResource("assets/images/main/ic_whatsapp.png",
      packageName: null);

  /// asset: assets/images/main/launch_background.webp
  // ignore: non_constant_identifier_names
  final launch_background_webp = const AssetResource(
      "assets/images/main/launch_background.webp",
      packageName: null);

  /// asset: assets/images/shoplink/ic_change_avatar.png
  // ignore: non_constant_identifier_names
  final ic_change_avatar = const AssetResource(
      "assets/images/shoplink/ic_change_avatar.png",
      packageName: null);

  /// asset: assets/images/shoplink/ic_edit.png
  // ignore: non_constant_identifier_names
  final ic_edit = const AssetResource("assets/images/shoplink/ic_edit.png",
      packageName: null);

  /// asset: assets/images/shoplink/ic_pv.png
  // ignore: non_constant_identifier_names
  final ic_pv = const AssetResource("assets/images/shoplink/ic_pv.png",
      packageName: null);

  /// asset: assets/images/store/bg_header.png
  // ignore: non_constant_identifier_names
  final bg_header = const AssetResource("assets/images/store/bg_header.png",
      packageName: null);

  /// asset: assets/images/store/default_portrait.png
  // ignore: non_constant_identifier_names
  final default_portrait = const AssetResource(
      "assets/images/store/default_portrait.png",
      packageName: null);

  /// asset: assets/images/store/ic_settings_contact.png
  // ignore: non_constant_identifier_names
  final ic_settings_contact = const AssetResource(
      "assets/images/store/ic_settings_contact.png",
      packageName: null);

  /// asset: assets/images/store/ic_settings_email.png
  // ignore: non_constant_identifier_names
  final ic_settings_email = const AssetResource(
      "assets/images/store/ic_settings_email.png",
      packageName: null);

  /// asset: assets/images/store/ic_settings_faq.png
  // ignore: non_constant_identifier_names
  final ic_settings_faq = const AssetResource(
      "assets/images/store/ic_settings_faq.png",
      packageName: null);

  /// asset: assets/images/store/ic_settings_privacy.png
  // ignore: non_constant_identifier_names
  final ic_settings_privacy = const AssetResource(
      "assets/images/store/ic_settings_privacy.png",
      packageName: null);

  /// asset: assets/images/store/ic_settings_rate_us.png
  // ignore: non_constant_identifier_names
  final ic_settings_rate_us = const AssetResource(
      "assets/images/store/ic_settings_rate_us.png",
      packageName: null);

  /// asset: assets/images/store/ic_settings_set_password.png
  // ignore: non_constant_identifier_names
  final ic_settings_set_password = const AssetResource(
      "assets/images/store/ic_settings_set_password.png",
      packageName: null);

  /// asset: assets/images/store/ic_tab_category_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_category_selected = const AssetResource(
      "assets/images/store/ic_tab_category_selected.png",
      packageName: null);

  /// asset: assets/images/store/ic_tab_category_unselected.png
  // ignore: non_constant_identifier_names
  final ic_tab_category_unselected = const AssetResource(
      "assets/images/store/ic_tab_category_unselected.png",
      packageName: null);

  /// asset: assets/images/store/ic_tab_product_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_product_selected = const AssetResource(
      "assets/images/store/ic_tab_product_selected.png",
      packageName: null);

  /// asset: assets/images/store/ic_tab_product_unselected.png
  // ignore: non_constant_identifier_names
  final ic_tab_product_unselected = const AssetResource(
      "assets/images/store/ic_tab_product_unselected.png",
      packageName: null);

  /// asset: assets/images/supply/ic_goods_share.png
  // ignore: non_constant_identifier_names
  final ic_goods_share = const AssetResource(
      "assets/images/supply/ic_goods_share.png",
      packageName: null);

  /// asset: assets/images/supply/ic_tab_supplier_hot_product_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_supplier_hot_product_selected = const AssetResource(
      "assets/images/supply/ic_tab_supplier_hot_product_selected.png",
      packageName: null);

  /// asset: assets/images/supply/ic_tab_supplier_hot_product_unselected.png
  // ignore: non_constant_identifier_names
  final ic_tab_supplier_hot_product_unselected = const AssetResource(
      "assets/images/supply/ic_tab_supplier_hot_product_unselected.png",
      packageName: null);

  /// asset: assets/images/supply/ic_tab_supplier_new_product_selected.png
  // ignore: non_constant_identifier_names
  final ic_tab_supplier_new_product_selected = const AssetResource(
      "assets/images/supply/ic_tab_supplier_new_product_selected.png",
      packageName: null);

  /// asset: assets/images/supply/ic_tab_supplier_new_product_unselected.png
  // ignore: non_constant_identifier_names
  final ic_tab_supplier_new_product_unselected = const AssetResource(
      "assets/images/supply/ic_tab_supplier_new_product_unselected.png",
      packageName: null);

  /// asset: assets/images/supply/pause.png
  // ignore: non_constant_identifier_names
  final pause =
      const AssetResource("assets/images/supply/pause.png", packageName: null);

  /// asset: assets/images/supply/play.png
  // ignore: non_constant_identifier_names
  final play =
      const AssetResource("assets/images/supply/play.png", packageName: null);
}

// ignore: camel_case_types
class _R_Svg_AssetResource {
  const _R_Svg_AssetResource();
}

// ignore: camel_case_types
class _R_Text_AssetResource {
  const _R_Text_AssetResource();
}

/// This `_R_Image` class is generated and contains references to static non-svg type image asset resources.
// ignore: camel_case_types
class _R_Image {
  const _R_Image();

  final asset = const _R_Image_AssetResource();

  /// asset: assets/images/avatar.png
  // ignore: non_constant_identifier_names
  AssetImage avatar() {
    return AssetImage(asset.avatar.keyName);
  }

  /// asset: assets/images/bg_congratulations.png
  // ignore: non_constant_identifier_names
  AssetImage bg_congratulations() {
    return AssetImage(asset.bg_congratulations.keyName);
  }

  /// asset: assets/images/bg_default_empty_goods.webp
  // ignore: non_constant_identifier_names
  AssetImage bg_default_empty_goods_webp() {
    return AssetImage(asset.bg_default_empty_goods_webp.keyName);
  }

  /// asset: assets/images/bg_default_empty_sales_history.webp
  // ignore: non_constant_identifier_names
  AssetImage bg_default_empty_sales_history_webp() {
    return AssetImage(asset.bg_default_empty_sales_history_webp.keyName);
  }

  /// asset: assets/images/bg_default_error.png
  // ignore: non_constant_identifier_names
  AssetImage bg_default_error() {
    return AssetImage(asset.bg_default_error.keyName);
  }

  /// asset: assets/images/bg_default_net_error.webp
  // ignore: non_constant_identifier_names
  AssetImage bg_default_net_error_webp() {
    return AssetImage(asset.bg_default_net_error_webp.keyName);
  }

  /// asset: assets/images/dashboard/bg_withdraw.webp
  // ignore: non_constant_identifier_names
  AssetImage bg_withdraw_webp() {
    return AssetImage(asset.bg_withdraw_webp.keyName);
  }

  /// asset: assets/images/dashboard/bg_withdraw_failure.webp
  // ignore: non_constant_identifier_names
  AssetImage bg_withdraw_failure_webp() {
    return AssetImage(asset.bg_withdraw_failure_webp.keyName);
  }

  /// asset: assets/images/dashboard/bg_withdraw_success.webp
  // ignore: non_constant_identifier_names
  AssetImage bg_withdraw_success_webp() {
    return AssetImage(asset.bg_withdraw_success_webp.keyName);
  }

  /// asset: assets/images/dashboard/ic_complete_rewards.png
  // ignore: non_constant_identifier_names
  AssetImage ic_complete_rewards() {
    return AssetImage(asset.ic_complete_rewards.keyName);
  }

  /// asset: assets/images/dashboard/ic_welcome_dialog.png
  // ignore: non_constant_identifier_names
  AssetImage ic_welcome_dialog() {
    return AssetImage(asset.ic_welcome_dialog.keyName);
  }

  /// asset: assets/images/ic_share_copy_link.png
  // ignore: non_constant_identifier_names
  AssetImage ic_share_copy_link() {
    return AssetImage(asset.ic_share_copy_link.keyName);
  }

  /// asset: assets/images/ic_share_download.png
  // ignore: non_constant_identifier_names
  AssetImage ic_share_download() {
    return AssetImage(asset.ic_share_download.keyName);
  }

  /// asset: assets/images/ic_share_facebook.png
  // ignore: non_constant_identifier_names
  AssetImage ic_share_facebook() {
    return AssetImage(asset.ic_share_facebook.keyName);
  }

  /// asset: assets/images/ic_share_instagram.png
  // ignore: non_constant_identifier_names
  AssetImage ic_share_instagram() {
    return AssetImage(asset.ic_share_instagram.keyName);
  }

  /// asset: assets/images/ic_share_more.png
  // ignore: non_constant_identifier_names
  AssetImage ic_share_more() {
    return AssetImage(asset.ic_share_more.keyName);
  }

  /// asset: assets/images/ic_share_twitter.png
  // ignore: non_constant_identifier_names
  AssetImage ic_share_twitter() {
    return AssetImage(asset.ic_share_twitter.keyName);
  }

  /// asset: assets/images/main/bg_login_signup.png
  // ignore: non_constant_identifier_names
  AssetImage bg_login_signup() {
    return AssetImage(asset.bg_login_signup.keyName);
  }

  /// asset: assets/images/main/ic_circle_logo.png
  // ignore: non_constant_identifier_names
  AssetImage ic_circle_logo() {
    return AssetImage(asset.ic_circle_logo.keyName);
  }

  /// asset: assets/images/main/ic_password_visibility.png
  // ignore: non_constant_identifier_names
  AssetImage ic_password_visibility() {
    return AssetImage(asset.ic_password_visibility.keyName);
  }

  /// asset: assets/images/main/ic_password_visibility_off.png
  // ignore: non_constant_identifier_names
  AssetImage ic_password_visibility_off() {
    return AssetImage(asset.ic_password_visibility_off.keyName);
  }

  /// asset: assets/images/main/ic_tab_biolinks_normal.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_biolinks_normal() {
    return AssetImage(asset.ic_tab_biolinks_normal.keyName);
  }

  /// asset: assets/images/main/ic_tab_biolinks_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_biolinks_selected() {
    return AssetImage(asset.ic_tab_biolinks_selected.keyName);
  }

  /// asset: assets/images/main/ic_tab_dashboard_normal.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_dashboard_normal() {
    return AssetImage(asset.ic_tab_dashboard_normal.keyName);
  }

  /// asset: assets/images/main/ic_tab_dashboard_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_dashboard_selected() {
    return AssetImage(asset.ic_tab_dashboard_selected.keyName);
  }

  /// asset: assets/images/main/ic_tab_inbox_normal.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_inbox_normal() {
    return AssetImage(asset.ic_tab_inbox_normal.keyName);
  }

  /// asset: assets/images/main/ic_tab_inbox_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_inbox_selected() {
    return AssetImage(asset.ic_tab_inbox_selected.keyName);
  }

  /// asset: assets/images/main/ic_tab_store_normal.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_store_normal() {
    return AssetImage(asset.ic_tab_store_normal.keyName);
  }

  /// asset: assets/images/main/ic_tab_store_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_store_selected() {
    return AssetImage(asset.ic_tab_store_selected.keyName);
  }

  /// asset: assets/images/main/ic_tab_supply_normal.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_supply_normal() {
    return AssetImage(asset.ic_tab_supply_normal.keyName);
  }

  /// asset: assets/images/main/ic_tab_supply_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_supply_selected() {
    return AssetImage(asset.ic_tab_supply_selected.keyName);
  }

  /// asset: assets/images/main/ic_whatsapp.png
  // ignore: non_constant_identifier_names
  AssetImage ic_whatsapp() {
    return AssetImage(asset.ic_whatsapp.keyName);
  }

  /// asset: assets/images/main/launch_background.webp
  // ignore: non_constant_identifier_names
  AssetImage launch_background_webp() {
    return AssetImage(asset.launch_background_webp.keyName);
  }

  /// asset: assets/images/shoplink/ic_change_avatar.png
  // ignore: non_constant_identifier_names
  AssetImage ic_change_avatar() {
    return AssetImage(asset.ic_change_avatar.keyName);
  }

  /// asset: assets/images/shoplink/ic_edit.png
  // ignore: non_constant_identifier_names
  AssetImage ic_edit() {
    return AssetImage(asset.ic_edit.keyName);
  }

  /// asset: assets/images/shoplink/ic_pv.png
  // ignore: non_constant_identifier_names
  AssetImage ic_pv() {
    return AssetImage(asset.ic_pv.keyName);
  }

  /// asset: assets/images/store/bg_header.png
  // ignore: non_constant_identifier_names
  AssetImage bg_header() {
    return AssetImage(asset.bg_header.keyName);
  }

  /// asset: assets/images/store/default_portrait.png
  // ignore: non_constant_identifier_names
  AssetImage default_portrait() {
    return AssetImage(asset.default_portrait.keyName);
  }

  /// asset: assets/images/store/ic_settings_contact.png
  // ignore: non_constant_identifier_names
  AssetImage ic_settings_contact() {
    return AssetImage(asset.ic_settings_contact.keyName);
  }

  /// asset: assets/images/store/ic_settings_email.png
  // ignore: non_constant_identifier_names
  AssetImage ic_settings_email() {
    return AssetImage(asset.ic_settings_email.keyName);
  }

  /// asset: assets/images/store/ic_settings_faq.png
  // ignore: non_constant_identifier_names
  AssetImage ic_settings_faq() {
    return AssetImage(asset.ic_settings_faq.keyName);
  }

  /// asset: assets/images/store/ic_settings_privacy.png
  // ignore: non_constant_identifier_names
  AssetImage ic_settings_privacy() {
    return AssetImage(asset.ic_settings_privacy.keyName);
  }

  /// asset: assets/images/store/ic_settings_rate_us.png
  // ignore: non_constant_identifier_names
  AssetImage ic_settings_rate_us() {
    return AssetImage(asset.ic_settings_rate_us.keyName);
  }

  /// asset: assets/images/store/ic_settings_set_password.png
  // ignore: non_constant_identifier_names
  AssetImage ic_settings_set_password() {
    return AssetImage(asset.ic_settings_set_password.keyName);
  }

  /// asset: assets/images/store/ic_tab_category_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_category_selected() {
    return AssetImage(asset.ic_tab_category_selected.keyName);
  }

  /// asset: assets/images/store/ic_tab_category_unselected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_category_unselected() {
    return AssetImage(asset.ic_tab_category_unselected.keyName);
  }

  /// asset: assets/images/store/ic_tab_product_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_product_selected() {
    return AssetImage(asset.ic_tab_product_selected.keyName);
  }

  /// asset: assets/images/store/ic_tab_product_unselected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_product_unselected() {
    return AssetImage(asset.ic_tab_product_unselected.keyName);
  }

  /// asset: assets/images/supply/ic_goods_share.png
  // ignore: non_constant_identifier_names
  AssetImage ic_goods_share() {
    return AssetImage(asset.ic_goods_share.keyName);
  }

  /// asset: assets/images/supply/ic_tab_supplier_hot_product_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_supplier_hot_product_selected() {
    return AssetImage(asset.ic_tab_supplier_hot_product_selected.keyName);
  }

  /// asset: assets/images/supply/ic_tab_supplier_hot_product_unselected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_supplier_hot_product_unselected() {
    return AssetImage(asset.ic_tab_supplier_hot_product_unselected.keyName);
  }

  /// asset: assets/images/supply/ic_tab_supplier_new_product_selected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_supplier_new_product_selected() {
    return AssetImage(asset.ic_tab_supplier_new_product_selected.keyName);
  }

  /// asset: assets/images/supply/ic_tab_supplier_new_product_unselected.png
  // ignore: non_constant_identifier_names
  AssetImage ic_tab_supplier_new_product_unselected() {
    return AssetImage(asset.ic_tab_supplier_new_product_unselected.keyName);
  }

  /// asset: assets/images/supply/pause.png
  // ignore: non_constant_identifier_names
  AssetImage pause() {
    return AssetImage(asset.pause.keyName);
  }

  /// asset: assets/images/supply/play.png
  // ignore: non_constant_identifier_names
  AssetImage play() {
    return AssetImage(asset.play.keyName);
  }
}

/// This `_R_Svg` class is generated and contains references to static svg type image asset resources.
// ignore: camel_case_types
class _R_Svg {
  const _R_Svg();

  final asset = const _R_Svg_AssetResource();
}

/// This `_R_Text` class is generated and contains references to static text asset resources.
// ignore: camel_case_types
class _R_Text {
  const _R_Text();

  final asset = const _R_Text_AssetResource();
}

/// This `_R_FontFamily` class is generated and contains references to static font asset resources.
// ignore: camel_case_types
class _R_FontFamily {
  const _R_FontFamily();
}
