export './module_main/home.dart';
export './module_main/splash.dart';
export './module_main/sign_up_sign_in.dart';
export './module_dashboard/dashboard_page.dart';
export './module_dashboard/balance.dart';
export './module_dashboard/withdraw.dart';
export './module_dashboard/rewards_detail.dart';
export './module_dashboard/withdraw_result.dart';
export './module_supply/supply_page.dart';