name: CI

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev' # or: 'beta' or 'dev'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build web
      - run: flutter build ipa
      - run: xcodebuild -exportArchive -allowProvisioningUpdates -archivePath ./build/ios/archive/Runner.xcarchive -exportPath ./build/idol.ipa -exportOptionsPlist exportOptions.plist

